services:
  documentstore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: documentstore
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: app
    ports:
      - "27017:27017"