version: '3.8'

services:
  documentstore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: documentstore
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/server", "-ping" ]
      interval: 30s
      timeout: 3s
      start_period: 5s