services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: support-chat-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq
    healthcheck:
      test: [ "CMD", "/server", "-ping" ]
      interval: 30s
      timeout: 3s
      start_period: 5s

  mongo:
    image: mongo:7.0
    container_name: support-chat-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: support

  rabbitmq:
    image: rabbitmq:3-management
    container_name: support-chat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest